# Generated by Django 2.0.2 on 2019-04-02 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contractor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Your Busniess name', max_length=256)),
                ('Money', models.PositiveIntegerField(help_text='Money for work')),
                ('Time', models.PositiveIntegerField(help_text='Time required for work')),
                ('area', models.PositiveIntegerField(help_text='area of work')),
                ('Image', models.ImageField(blank=True, help_text='proposed work image', null=True, upload_to='')),
                ('email', models.EmailField(help_text='Email to connect you', max_length=254)),
                ('Status', models.CharField(blank=True, choices=[('APPROVED', 'AP'), ('NOT APPROVED', 'NP')], max_length=230, null=True)),
                ('Reason', models.CharField(blank=True, max_length=230, null=True)),
            ],
        ),
    ]
