# Generated by Django 2.2 on 2019-04-02 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contra', '0002_school'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='Amentier_Required',
            field=models.CharField(blank=True, max_length=234, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='Contractor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='contra.Contractor'),
        ),
        migrations.AddField(
            model_name='school',
            name='School_level',
            field=models.CharField(blank=True, max_length=234, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='Teacher',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='school_Area',
            field=models.CharField(blank=True, max_length=234, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='student',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='support_staff',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
