# Generated by Django 2.2 on 2019-04-02 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contra', '0004_contractor_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='Contractor',
            new_name='contractor',
        ),
    ]
