# Generated by Django 2.2 on 2019-04-02 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='Auditor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Contractor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='District_Officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='HeadMaster',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Mandal_Officer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='Sec',
            field=models.BooleanField(default=False),
        ),
    ]
